import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Activity, Bot, ChevronDown, Clock3, GripVertical, History, Home, ListMusic, Music2, Pause, Play, Plus, Radio, RotateCcw, Search, Settings, SkipForward, Square, Trash2, Volume2, Wifi, Zap } from 'lucide-react';
import type { BotEvent, Command, Config, Library, PlayerState, Playlist, Track } from './types';

const initialState: PlayerState = { connected:false, botOnline:false, guildId:'', guildName:'Aucun serveur', guilds:[], textChannels:[], voiceChannel:'Aucun salon', playing:false, volume:64, position:0, elapsed:0, current:null, queue:[], history:[] };
const tabs = [{id:'home',label:'Accueil',icon:Home},{id:'search',label:'Recherche',icon:Search},{id:'playlists',label:'Playlists',icon:Music2},{id:'queue',label:'Queue',icon:ListMusic},{id:'history',label:'Historique',icon:History},{id:'settings',label:'Paramètres',icon:Settings}];
const rid=()=>Math.random().toString(36).slice(2);
function decode(s:string){ const t=document.createElement('textarea');t.innerHTML=s;return t.value }
function isoDuration(s:string){ if(!s.startsWith('P')) return s; const m=s.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/); if(!m)return s; const h=Number(m[1]||0),n=Number(m[2]||0),x=Number(m[3]||0); return `${h?`${h}:`:''}${String(n).padStart(h?2:1,'0')}:${String(x).padStart(2,'0')}` }
function seconds(s:string){if(!s||s==='LIVE')return 0;const p=s.split(':').map(Number);return p.some(Number.isNaN)?0:p.reduce((a,b)=>a*60+b,0)}

export default function App(){
  const [tab,setTab]=useState('home'); const [config,setConfig]=useState<Config|null>(null); const [state,setState]=useState(initialState);
  const [library,setLibrary]=useState<Library>({history:[],playlists:[]}); const previousTrack=useRef<Track|null>(null);
  const [notice,setNotice]=useState(''); const [logs,setLogs]=useState(''); const socket=useRef<WebSocket|null>(null); const reconnect=useRef<number>();
  const demo=config?.demoMode;
  const connect=()=>{ if(!config||config.demoMode)return; window.clearTimeout(reconnect.current); socket.current?.close(); try{
    const ws=new WebSocket(config.wsUrl); socket.current=ws;
    ws.onopen=()=>{ const context={discordUserId:config.discordUserId,preferredGuildId:config.preferredGuildId,preferredTextChannelId:config.preferredTextChannelId}; setState(s=>({...s,connected:true})); ws.send(JSON.stringify({type:'auth',token:config.apiToken})); ws.send(JSON.stringify({type:'command',action:'get_state',requestId:rid(),context})); };
    ws.onmessage=e=>{ try{ const msg:BotEvent=JSON.parse(e.data); if(msg.type==='state')setState(s=>({...s,...msg.payload,connected:true})); else if(msg.type==='event'){const result=msg.payload as {ok?:boolean;message?:string};if(result?.ok===false)setNotice(result.message||'Commande refusée par le bot.')}}catch{} };
    ws.onclose=()=>{setState(s=>({...s,connected:false,botOnline:false}));reconnect.current=window.setTimeout(connect,3000)};
  }catch(e){setNotice(String(e))} };
  useEffect(()=>{window.newaa.getConfig().then(c=>{setConfig(c);if(c.demoMode)setState({...initialState,connected:true,botOnline:true,guildName:'Mode démonstration',voiceChannel:'Aucun salon',playing:false,current:null,queue:[],history:[]})});window.newaa.getLibrary().then(setLibrary);const offLog=window.newaa.onBotLog(x=>setLogs(v=>(v+x).slice(-12000)));const offUpdate=window.newaa.onUpdate(x=>{if(x.state==='downloading')setNotice(`Mise à jour ${x.version} en téléchargement…`);if(x.state==='progress')setNotice(`Téléchargement de la mise à jour : ${x.percent}%`);if(x.state==='ready')setNotice(`Mise à jour ${x.version} prête, redémarrage…`)});return()=>{offLog();offUpdate()}},[]);
  useEffect(()=>{const current=state.current;if(previousTrack.current&&previousTrack.current.id!==current?.id){const old=previousTrack.current;setLibrary(l=>{const next={...l,history:[old,...l.history.filter(x=>x.id!==old.id)].slice(0,200)};window.newaa.saveLibrary(next);return next})}previousTrack.current=current},[state.current?.id]);
  const saveLibrary=(next:Library)=>{setLibrary(next);window.newaa.saveLibrary(next)};
  const addToPlaylist=(playlistId:string,track:Track)=>{const next={...library,playlists:library.playlists.map(p=>p.id===playlistId?{...p,tracks:[...p.tracks.filter(x=>x.id!==track.id),track]}:p)};saveLibrary(next);setNotice('Ajouté à la playlist.')} ;
  useEffect(()=>{if(config)connect(); return()=>{window.clearTimeout(reconnect.current);socket.current?.close()}},[config?.wsUrl,config?.apiToken,config?.demoMode]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(t)},[notice]);
  useEffect(()=>{if(!state.playing||!state.current)return;const timer=window.setInterval(()=>setState(s=>{if(!s.playing||!s.current)return s;const elapsed=s.elapsed+1,total=seconds(s.current.duration);return{...s,elapsed,position:total?Math.min(100,elapsed/total*100):0}}),1000);return()=>window.clearInterval(timer)},[state.playing,state.current?.id]);
  const send=(action:string,payload?:unknown)=>{
    if(demo){ demoCommand(action,payload); return }
    if(socket.current?.readyState!==WebSocket.OPEN){setNotice('Le bot n’est pas connecté.');return}
    const context={discordUserId:config?.discordUserId||'',preferredGuildId:config?.preferredGuildId||'',preferredTextChannelId:config?.preferredTextChannelId||''};
    const message:Command={type:'command',action,payload,requestId:rid(),context};socket.current.send(JSON.stringify(message));
  };
  const demoCommand=(action:string,payload?:unknown)=>setState(s=>{
    if(action==='toggle_pause')return{...s,playing:!s.playing}; if(action==='volume')return{...s,volume:Number(payload)};
    if(action==='stop')return{...s,playing:false,current:null,queue:[]}; if(action==='skip'){const [next,...rest]=s.queue;return{...s,current:next||null,queue:rest,history:s.current?[s.current,...s.history]:s.history,playing:!!next}}
    if(action==='play_now'){const t=payload as Track;return{...s,current:t,playing:true,history:s.current?[s.current,...s.history]:s.history}}
    if(action==='enqueue'){return{...s,queue:[...s.queue,payload as Track]}} if(action==='play_next'){return{...s,queue:[payload as Track,...s.queue]}}
    if(action==='remove_queue'){return{...s,queue:s.queue.filter((_,i)=>i!==Number(payload))}} if(action==='clear_queue')return{...s,queue:[]}; if(action==='reorder_queue')return{...s,queue:payload as Track[]}; return s;
  });
  if(!config)return <div className="loading"><Music2/> Chargement de NEWAA Music…</div>;
  return <div className="app">
    <aside><div className="brand"><div className="brandmark"><Music2/></div><div><b>NEWAA</b><span>MUSIC CONTROL</span></div></div>
      <nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon/> {t.label}{t.id==='queue'&&state.queue.length>0?<i>{state.queue.length}</i>:null}</button>)}</nav>
      <div className="aside-bottom"><div className={`connection ${state.connected?'ok':''}`}><span/><div><b>{state.connected?'Connecté':'Déconnecté'}</b><small>{demo?'Mode démonstration':config.wsUrl.replace('ws://','')}</small></div></div><button className="profile"><div>N</div><span><b>NEWAA</b><small>Administrateur</small></span><ChevronDown/></button></div>
    </aside>
    <main><header><div><p>{tabs.find(x=>x.id===tab)?.label}</p><h1>{tab==='home'?'Bonsoir, NEWAA.':tab==='search'?'Trouve le prochain son.':tab==='playlists'?'Tes playlists':tab==='queue'?'File d’attente':tab==='history'?'Dernières écoutes':'Configuration'}</h1></div><ServerPicker state={state} select={id=>send('select_guild',id)}/></header>
      <section className="content">{tab==='home'&&<HomePage state={state} send={send} go={setTab}/>} {tab==='search'&&<SearchPage send={send} playlists={library.playlists} addToPlaylist={addToPlaylist}/>} {tab==='playlists'&&<PlaylistsPage playlists={library.playlists} save={playlists=>saveLibrary({...library,playlists})} send={send}/>} {tab==='queue'&&<QueuePage state={state} send={send}/>} {tab==='history'&&<HistoryPage history={library.history} send={send} clear={()=>saveLibrary({...library,history:[]})}/>} {tab==='settings'&&<SettingsPage config={config} state={state} save={async c=>{setConfig(await window.newaa.setConfig(c));setNotice('Configuration enregistrée.')}} logs={logs} notice={setNotice}/>}</section>
    </main>
    <Player state={state} send={send}/>{notice&&<div className="toast">{notice}</div>}
  </div>
}

function ServerPicker({state,select}:{state:PlayerState;select:(id:string)=>void}){const[open,setOpen]=useState(false);return <div className="server-wrap"><button className="server" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><Radio/><span><small>SERVEUR ACTIF</small><b>{state.guildName}</b></span><ChevronDown className={open?'rotated':''}/></button>{open&&<div className="server-menu">{state.guilds.length?state.guilds.map(g=><button key={g.id} className={g.id===state.guildId?'selected':''} onClick={()=>{select(g.id);setOpen(false)}}><span>{g.icon?<img src={g.icon}/>:g.name.slice(0,1).toUpperCase()}</span><div><b>{g.name}</b><small>{g.id===state.guildId?'Serveur actif':'Choisir ce serveur'}</small></div>{g.id===state.guildId&&<i/>}</button>):<p>Le bot n’est présent sur aucun serveur.</p>}</div>}</div>}

function HomePage({state,send,go}:{state:PlayerState;send:(a:string,p?:unknown)=>void;go:(x:string)=>void}){return <>
  <div className="status-grid"><article><div className="status-icon purple"><Bot/></div><div><small>ÉTAT DU BOT</small><h3>{state.botOnline?'En ligne':'Hors ligne'}</h3><p><span className={state.botOnline?'dot':''}/> {state.connected?'Latence temps réel active':'Connexion indisponible'}</p></div></article><article><div className="status-icon pink"><Wifi/></div><div><small>SALON VOCAL</small><h3>{state.voiceChannel}</h3><p>{state.botOnline?'Connecté et prêt à jouer':'Le bot doit rejoindre un salon'}</p></div></article><article><div className="status-icon blue"><ListMusic/></div><div><small>FILE D’ATTENTE</small><h3>{state.queue.length} titre{state.queue.length!==1?'s':''}</h3><p>{state.queue.length?`À suivre : ${state.queue[0].title.slice(0,25)}`:'Ajoute de la musique'}</p></div></article></div>
  <div className="home-grid"><article className="now-card"><div className="eyebrow"><span>LECTURE EN COURS</span><Activity/></div>{state.current?<><img src={state.current.thumbnail}/><div className="now-info"><h2>{state.current.title}</h2><p>{state.current.channel}</p><div className="wave">{Array.from({length:34}).map((_,i)=><i key={i} style={{height:`${12+(i*17)%38}px`}}/>)}</div><div className="hero-controls"><button onClick={()=>send('toggle_pause')} className="hero-play">{state.playing?<Pause/>:<Play/>}</button><button onClick={()=>send('skip')}><SkipForward/></button><button onClick={()=>send('stop')}><Square/></button></div></div></>:<div className="empty big"><Music2/><h3>Rien ne joue</h3><button onClick={()=>go('search')}>Rechercher une vidéo</button></div>}</article>
    <article className="quick"><div className="section-title"><div><small>CONTRÔLE RAPIDE</small><h2>À suivre</h2></div><button onClick={()=>go('queue')}>Voir la queue</button></div>{state.queue.slice(0,4).map((t,i)=><TrackRow key={t.id+i} t={t} index={i+1} action={<button onClick={()=>send('remove_queue',i)}><Trash2/></button>}/>)}{!state.queue.length&&<div className="empty"><ListMusic/><p>La file est vide.</p></div>}<button className="search-cta" onClick={()=>go('search')}><Plus/> Ajouter de la musique</button></article></div></>}

function SearchPage({send,playlists,addToPlaylist}:{send:(a:string,p?:unknown)=>void;playlists:Playlist[];addToPlaylist:(id:string,t:Track)=>void}){const[q,setQ]=useState('');const[items,setItems]=useState<Track[]>([]);const[selected,setSelected]=useState<Track|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[token,setToken]=useState('');
 const search=async(more=false)=>{if(!q.trim())return;setLoading(true);setError('');try{const r=await window.newaa.searchYouTube(q,more?token:'');const clean=r.items.map(x=>({...x,title:decode(x.title),channel:decode(x.channel),duration:isoDuration(x.duration)}));setItems(v=>more?[...v,...clean]:clean);setToken(r.nextPageToken)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 return <><form className="searchbar" onSubmit={e=>{e.preventDefault();search()}}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher une musique, un artiste ou coller un lien YouTube…"/><button>Rechercher</button></form>{error&&<div className="error">{error}</div>}
 {!items.length&&!loading?<div className="search-empty"><div><Search/></div><h2>Qu’est-ce qu’on écoute ?</h2><p>Les résultats YouTube apparaîtront ici avec leur miniature, chaîne et durée.</p><div className="suggestions">{['lofi hip hop','musique gaming','mix années 2000'].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div></div>:<div className="video-grid">{items.map(t=><button className="video" key={t.id} onClick={()=>setSelected(t)}><div><img src={t.thumbnail}/><span>{t.duration}</span><i><Play/></i></div><h3>{t.title}</h3><p>{t.channel}</p></button>)}</div>}{loading&&<div className="spinner"/>}{token&&!loading&&<button className="load-more" onClick={()=>search(true)}>Afficher plus</button>}
 {selected&&<div className="modalback" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><img src={selected.thumbnail}/><small>VIDÉO SÉLECTIONNÉE</small><h2>{selected.title}</h2><p>{selected.channel} · {selected.duration}</p><div><button onClick={()=>{send('play_now',selected);setSelected(null)}} className="primary"><Play/> Lire maintenant</button><button onClick={()=>{send('play_next',selected);setSelected(null)}}><Zap/> Lire ensuite</button><button onClick={()=>{send('enqueue',selected);setSelected(null)}}><Plus/> Ajouter à la file</button></div>{playlists.length?<label className="playlist-select">Ajouter à une playlist<select defaultValue="" onChange={e=>{if(e.target.value){addToPlaylist(e.target.value,selected);setSelected(null)}}}><option value="" disabled>Choisir…</option>{playlists.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:<p className="playlist-tip">Crée d’abord une playlist dans l’onglet Playlists.</p>}</div></div>}</>}

function QueuePage({state,send}:{state:PlayerState;send:(a:string,p?:unknown)=>void}){const[drag,setDrag]=useState<number|null>(null);const drop=(to:number)=>{if(drag===null||drag===to)return;const q=[...state.queue];const[x]=q.splice(drag,1);q.splice(to,0,x);send('reorder_queue',q);setDrag(null)};return <article className="panel"><div className="section-title"><div><small>PROCHAINS TITRES</small><h2>{state.queue.length} musique{state.queue.length!==1?'s':''}</h2></div>{state.queue.length>0&&<button onClick={()=>send('clear_queue')}><Trash2/> Vider la file</button>}</div><div className="queue-head"><span>#</span><span>TITRE</span><span>DEMANDÉ PAR</span><span>DURÉE</span><span/></div>{state.queue.map((t,i)=><div className="queue-row" draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(i)} key={`${t.id}-${i}`}><GripVertical/><b>{i+1}</b><img src={t.thumbnail}/><div><strong>{t.title}</strong><small>{t.channel}</small></div><span>{t.requestedBy||'Desktop'}</span><span>{t.duration}</span><button onClick={()=>send('remove_queue',i)}><Trash2/></button></div>)}{!state.queue.length&&<div className="empty big"><ListMusic/><h3>Ta file est vide</h3><p>Ajoute des vidéos depuis l’onglet Recherche.</p></div>}</article>}
function HistoryPage({history,send,clear}:{history:Track[];send:(a:string,p?:unknown)=>void;clear:()=>void}){return <article className="panel"><div className="section-title"><div><small>HISTORIQUE LOCAL PERSISTANT</small><h2>Récemment écouté</h2></div>{history.length>0&&<button onClick={clear}><Trash2/> Effacer</button>}</div>{history.map((t,i)=><TrackRow key={t.id+i} t={t} index={i+1} action={<button className="replay" onClick={()=>send('play_now',t)}><RotateCcw/> Rejouer</button>}/>)}{!history.length&&<div className="empty big"><Clock3/><h3>Aucune écoute récente</h3><p>Chaque morceau passé ou remplacé sera conservé ici.</p></div>}</article>}

function PlaylistsPage({playlists,save,send}:{playlists:Playlist[];save:(p:Playlist[])=>void;send:(a:string,p?:unknown)=>void}){const[name,setName]=useState('');const[selected,setSelected]=useState(playlists[0]?.id||'');const active=playlists.find(p=>p.id===selected)||playlists[0];const create=()=>{const n=name.trim();if(!n)return;const p={id:rid(),name:n,createdAt:Date.now(),tracks:[]};save([...playlists,p]);setSelected(p.id);setName('')};const removeTrack=(id:string)=>active&&save(playlists.map(p=>p.id===active.id?{...p,tracks:p.tracks.filter(t=>t.id!==id)}:p));return <div className="playlists-layout"><article className="panel playlist-sidebar"><div className="section-title"><div><small>TA BIBLIOTHÈQUE</small><h2>Playlists</h2></div></div><form onSubmit={e=>{e.preventDefault();create()}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom de la playlist"/><button className="primary"><Plus/> Créer</button></form>{playlists.map(p=><button className={active?.id===p.id?'active':''} key={p.id} onClick={()=>setSelected(p.id)}><Music2/><span><b>{p.name}</b><small>{p.tracks.length} titre{p.tracks.length!==1?'s':''}</small></span></button>)}</article><article className="panel playlist-detail">{active?<><div className="section-title"><div><small>PLAYLIST</small><h2>{active.name}</h2></div><div className="playlist-actions"><button onClick={()=>active.tracks.forEach(t=>send('enqueue',t))}><Plus/> Ajouter à la file</button><button onClick={()=>{active.tracks.forEach((t,i)=>send(i===0?'play_now':'enqueue',t))}}><Play/> Tout lire</button><button onClick={()=>{save(playlists.filter(p=>p.id!==active.id));setSelected('')}}><Trash2/></button></div></div>{active.tracks.map((t,i)=><TrackRow key={t.id+i} t={t} index={i+1} action={<div className="track-actions"><button onClick={()=>send('play_now',t)}><Play/></button><button onClick={()=>removeTrack(t.id)}><Trash2/></button></div>}/>)}{!active.tracks.length&&<div className="empty big"><Music2/><h3>Playlist vide</h3><p>Ajoute des morceaux depuis la recherche.</p></div>}</>:<div className="empty big"><Music2/><h3>Crée ta première playlist</h3><p>Tu n’auras plus besoin de rechercher les mêmes morceaux.</p></div>}</article></div>}
function TrackRow({t,index,action}:{t:Track;index:number;action:ReactNode}){return <div className="track-row"><b>{String(index).padStart(2,'0')}</b><img src={t.thumbnail}/><div><strong>{t.title}</strong><small>{t.channel}</small></div><span>{t.duration}</span>{action}</div>}

function SettingsPage({config,state,save,logs,notice}:{config:Config;state:PlayerState;save:(c:Config)=>void;logs:string;notice:(s:string)=>void}){const[c,setC]=useState(config);return <div className="settings-grid"><article className="panel"><div className="section-title"><div><small>CONNEXION</small><h2>Bot Discord</h2></div><div className={`pill ${c.demoMode?'demo':''}`}>{c.demoMode?'Démonstration':'Production'}</div></div><label className="toggle"><span><b>Mode démonstration</b><small>Teste toute l’interface sans bot connecté.</small></span><input type="checkbox" checked={c.demoMode} onChange={e=>setC({...c,demoMode:e.target.checked})}/><i/></label><Field label="Ton identifiant utilisateur Discord" value={c.discordUserId} onChange={v=>setC({...c,discordUserId:v.replace(/\D/g,'')})} placeholder="Ex. 123456789012345678"/><p className="setting-help">Le bot utilise cet identifiant public pour te retrouver. Aucun token Discord utilisateur n’est demandé ou enregistré.</p><SelectField label="Serveur préféré" value={c.preferredGuildId} onChange={v=>setC({...c,preferredGuildId:v,preferredTextChannelId:''})} options={state.guilds}/><SelectField label="Salon textuel pour les messages" value={c.preferredTextChannelId} onChange={v=>setC({...c,preferredTextChannelId:v})} options={state.textChannels}/><div className="subhead"><Wifi/><div><b>Salon vocal automatique</b><small>Le bot rejoint uniquement le salon vocal dans lequel tu te trouves.</small></div></div><button className="primary save" onClick={()=>save(c)}>Enregistrer</button></article>
 <article className="panel"><div className="section-title"><div><small>PROCESSUS LOCAL</small><h2>Démarrage du bot</h2></div></div><Field label="Dossier du bot" value={c.botCwd} onChange={v=>setC({...c,botCwd:v})} placeholder="C:\\Bots\\NEWAA-Music"/><Field label="Commande" value={c.botCommand} onChange={v=>setC({...c,botCommand:v})} placeholder="npm start"/><div className="bot-buttons"><button onClick={async()=>notice((await window.newaa.startBot()).message)}><Play/> Démarrer</button><button onClick={async()=>notice((await window.newaa.stopBot()).message)}><Square/> Arrêter</button></div><div className="console"><div><span/><span/><span/><b>Logs du bot</b></div><pre>{logs||'En attente de logs…'}</pre></div></article></div>}
function Field({label,value,onChange,placeholder,secret=false}:{label:string;value:string;onChange:(s:string)=>void;placeholder:string;secret?:boolean}){return <label className="field"><span>{label}</span><input type={secret?'password':'text'} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:{id:string;name:string}[]}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Automatique / aucun</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function clock(total:number){const s=Math.max(0,Math.floor(total||0)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return `${h?`${h}:`:''}${h?String(m).padStart(2,'0'):m}:${String(r).padStart(2,'0')}`}
function Player({state,send}:{state:PlayerState;send:(a:string,p?:unknown)=>void}){return <footer><div className="mini-track">{state.current?<><img src={state.current.thumbnail}/><div><b>{state.current.title}</b><span>{state.current.channel}</span></div></>:<><div className="mini-empty"><Music2/></div><div><b>Aucune lecture</b><span>Choisis une vidéo</span></div></>}</div><div className="footer-center"><div><button onClick={()=>send('toggle_pause')} className="play">{state.playing?<Pause/>:<Play/>}</button><button onClick={()=>send('skip')}><SkipForward/></button><button onClick={()=>send('stop')}><Square/></button></div><SeekBar state={state} send={send}/></div><div className="volume"><Volume2/><input type="range" min="0" max="100" value={state.volume} onChange={e=>send('volume',Number(e.target.value))}/><b>{state.volume}%</b></div></footer>}

function SeekBar({state,send}:{state:PlayerState;send:(a:string,p?:unknown)=>void}){
  const total=seconds(state.current?.duration||'');
  const[preview,setPreview]=useState<number|null>(null);
  useEffect(()=>setPreview(null),[state.current?.id]);
  const value=preview??Math.min(total,state.elapsed);
  const commit=(target:number)=>{setPreview(null);if(state.current&&total>0)send('seek',target)};
  return <div className="timeline"><span>{clock(value)}</span><input className="seekbar" aria-label="Position de lecture" type="range" min="0" max={Math.max(1,total)} step="1" value={value} disabled={!state.current||total<=0} onChange={e=>setPreview(Number(e.target.value))} onPointerUp={e=>commit(Number(e.currentTarget.value))} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key))commit(Number(e.currentTarget.value))}}/><span>{state.current?.duration||'0:00'}</span></div>
}
