export type Track = { id: string; title: string; channel: string; thumbnail: string; duration: string; requestedBy?: string };
export type Playlist = { id:string; name:string; createdAt:number; tracks:Track[]; visibility?:'private'|'public'; shareKey?:string; ownerName?:string; ownerAvatar?:string };
export type ListeningStats = { totalSeconds:number; tracksPlayed:number; playCount:Record<string,number>; lastPlayedAt:number };
export type Library = { history:Track[]; playlists:Playlist[]; favorites:Track[]; pinned:Track[]; stats:ListeningStats };
export type ChannelChoice = { id:string; name:string };
export type VoiceMember = { id:string; name:string; avatar:string; bot:boolean };
export type PlayerState = { connected: boolean; botOnline: boolean; latencyMs:number; discordClientId: string; userName: string; userAvatar: string; guildId: string; guildName: string; guilds: {id:string;name:string;icon?:string}[]; textChannels: ChannelChoice[]; voiceChannel: string; voiceMembers: VoiceMember[]; playing: boolean; volume: number; audioPreset:'normal'|'bass'|'vocal'|'night'; normalizeVolume:boolean; crossfadeSeconds:number; position: number; elapsed: number; current: Track | null; queue: Track[]; history: Track[] };
export type Config = { wsUrl: string; apiToken: string; youtubeApiKey: string; botCommand: string; botCwd: string; demoMode: boolean; theme:'inazuma'|'midnight'|'ember'; discordClientId: string; discordUserId: string; discordUserName: string; discordAvatar: string; preferredGuildId: string; preferredTextChannelId: string; autoJoin: boolean; autoLeave: boolean; controlMode:'private'|'shared'; allowedRoleIds:string; audioPreset:'normal'|'bass'|'vocal'|'night'; normalizeVolume:boolean; crossfadeSeconds:number; presenceEnabled: boolean; presenceDetails: string; presenceLinkLabel: string; presenceLinkUrl: string; presenceDownloadLabel: string; presenceDownloadUrl: string };
export type CommandContext = { discordUserId:string; preferredGuildId:string; preferredTextChannelId:string; autoJoin:boolean; autoLeave:boolean; controlMode:'private'|'shared'; allowedRoleIds:string; audioPreset:'normal'|'bass'|'vocal'|'night'; normalizeVolume:boolean; crossfadeSeconds:number };
export type Command = { type: 'command'; action: string; payload?: unknown; requestId: string; context: CommandContext };
export type BotEvent = { type: 'state'; payload: Partial<PlayerState> } | { type: 'event'; event: string; payload: unknown };
declare global { interface Window { newaa: { getConfig(): Promise<Config>; setConfig(c: Config): Promise<Config>; getLibrary():Promise<Library>; saveLibrary(library:Library):Promise<Library>; searchYouTube(q: string, token?: string): Promise<{items: Track[]; nextPageToken: string}>; searchLyrics(title:string,artist?:string):Promise<{trackName:string;artistName:string;duration:number;syncedLyrics:string;plainLyrics:string;instrumental:boolean}|null>; getPublicPlaylists(q?:string):Promise<Playlist[]>; publishPlaylist(playlist:Playlist):Promise<void>; unpublishPlaylist(id:string,shareKey:string):Promise<void>; loginDiscord(clientId:string):Promise<{id:string;name:string;avatar:string}>; startBot(): Promise<{message:string}>; stopBot(): Promise<{message:string}>; openExternal(url:string): Promise<void>; getAppInfo():Promise<{name:string;version:string}>; toggleMiniPlayer():Promise<boolean>; notifyTrack(track:Track):Promise<void>; quitApp():Promise<void>; onBotLog(cb:(line:string)=>void):()=>void; onUpdate(cb:(event:{state:string;version?:string;percent?:number})=>void):()=>void; onMediaCommand(cb:(action:string)=>void):()=>void } } }
