export type Track = { id: string; title: string; channel: string; thumbnail: string; duration: string; requestedBy?: string };
export type Playlist = { id:string; name:string; createdAt:number; tracks:Track[]; visibility?:'private'|'public'; shareKey?:string; ownerName?:string; ownerAvatar?:string };
export type Library = { history:Track[]; playlists:Playlist[] };
export type ChannelChoice = { id:string; name:string };
export type VoiceMember = { id:string; name:string; avatar:string; bot:boolean };
export type PlayerState = { connected: boolean; botOnline: boolean; discordClientId: string; userName: string; userAvatar: string; guildId: string; guildName: string; guilds: {id:string;name:string;icon?:string}[]; textChannels: ChannelChoice[]; voiceChannel: string; voiceMembers: VoiceMember[]; playing: boolean; volume: number; position: number; elapsed: number; current: Track | null; queue: Track[]; history: Track[] };
export type Config = { wsUrl: string; apiToken: string; youtubeApiKey: string; botCommand: string; botCwd: string; demoMode: boolean; discordClientId: string; discordUserId: string; discordUserName: string; discordAvatar: string; preferredGuildId: string; preferredTextChannelId: string; autoJoin: boolean; autoLeave: boolean; presenceEnabled: boolean; presenceDetails: string; presenceLinkLabel: string; presenceLinkUrl: string; presenceDownloadLabel: string; presenceDownloadUrl: string };
export type CommandContext = { discordUserId:string; preferredGuildId:string; preferredTextChannelId:string; autoJoin:boolean; autoLeave:boolean };
export type Command = { type: 'command'; action: string; payload?: unknown; requestId: string; context: CommandContext };
export type BotEvent = { type: 'state'; payload: Partial<PlayerState> } | { type: 'event'; event: string; payload: unknown };
declare global { interface Window { newaa: { getConfig(): Promise<Config>; setConfig(c: Config): Promise<Config>; getLibrary():Promise<Library>; saveLibrary(library:Library):Promise<Library>; searchYouTube(q: string, token?: string): Promise<{items: Track[]; nextPageToken: string}>; getPublicPlaylists(q?:string):Promise<Playlist[]>; publishPlaylist(playlist:Playlist):Promise<void>; unpublishPlaylist(id:string,shareKey:string):Promise<void>; loginDiscord(clientId:string):Promise<{id:string;name:string;avatar:string}>; startBot(): Promise<{message:string}>; stopBot(): Promise<{message:string}>; openExternal(url:string): Promise<void>; getAppInfo():Promise<{name:string;version:string}>; quitApp():Promise<void>; onBotLog(cb:(line:string)=>void):()=>void; onUpdate(cb:(event:{state:string;version?:string;percent?:number})=>void):()=>void } } }
